using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 滚动视图使用示例
/// 展示如何在代码中使用UniversalScrollView
/// </summary>
public class ScrollViewExample : MonoBehaviour
{
    [Header("滚动视图引用")]
    [SerializeField] private UniversalScrollView scrollView;

    [Header("测试数据")]
    [SerializeField] private int testDataCount = 10;
    [SerializeField] private bool autoGenerateData = true;

    private List<ISetComScrollItem> testData = new List<ISetComScrollItem>();

    private void Start()
    {
        InitializeScrollView();

        if (autoGenerateData)
        {
            GenerateTestData();
        }
    }

    /// <summary>
    /// 初始化滚动视图
    /// </summary>
    private void InitializeScrollView()
    {
        if (scrollView == null)
        {
            scrollView = GetComponent<UniversalScrollView>();
        }

        if (scrollView == null)
        {
            Debug.LogError("ScrollViewExample: 未找到UniversalScrollView组件！");
            return;
        }
    }

    /// <summary>
    /// 生成测试数据
    /// </summary>
    private void GenerateTestData()
    {
        testData.Clear();

        for (int i = 0; i < testDataCount; i++)
        {
            testData.Add(new ISetComScrollItem { index = i });
        }

        // 设置数据到滚动视图
        scrollView.SetData(testData);

        Debug.Log($"已生成 {testDataCount} 个测试数据项");
    }

    #region 公共方法（供UI按钮调用）

    /// <summary>
    /// 添加新项目
    /// </summary>
    [ContextMenu("添加新项目")]
    public void AddNewItem()
    {
        if (scrollView != null)
        {
            var newItem = new ISetComScrollItem { index = testData.Count };
            testData.Add(newItem);
            scrollView.AddItem(newItem);

            Debug.Log($"添加了新项目，索引: {newItem.index}");
        }
    }

    /// <summary>
    /// 移除最后一个项目
    /// </summary>
    [ContextMenu("移除最后项目")]
    public void RemoveLastItem()
    {
        if (scrollView != null && testData.Count > 0)
        {
            int lastIndex = testData.Count - 1;
            testData.RemoveAt(lastIndex);
            scrollView.RemoveItem(lastIndex);

            Debug.Log($"移除了项目，索引: {lastIndex}");
        }
    }

    /// <summary>
    /// 清空所有项目
    /// </summary>
    [ContextMenu("清空所有项目")]
    public void ClearAllItems()
    {
        if (scrollView != null)
        {
            testData.Clear();
            scrollView.ClearData();

            Debug.Log("已清空所有项目");
        }
    }

    /// <summary>
    /// 切换滚动方向
    /// </summary>
    [ContextMenu("切换滚动方向")]
    public void ToggleScrollDirection()
    {
        if (scrollView != null)
        {
            var currentDirection = scrollView.GetScrollDirection();
            var newDirection = currentDirection == UniversalScrollView.ScrollDirection.Vertical ?
                UniversalScrollView.ScrollDirection.Horizontal :
                UniversalScrollView.ScrollDirection.Vertical;

            scrollView.SetScrollDirection(newDirection);

            Debug.Log($"滚动方向已切换为: {newDirection}");
        }
    }

    /// <summary>
    /// 设置容器尺寸为手机竖屏
    /// </summary>
    [ContextMenu("设置为手机竖屏尺寸")]
    public void SetPhonePortraitSize()
    {
        if (scrollView != null)
        {
            scrollView.SetContainerSize(375f, 667f);
            Debug.Log("容器尺寸已设置为手机竖屏 (375x667)");
        }
    }

    /// <summary>
    /// 设置容器尺寸为手机横屏
    /// </summary>
    [ContextMenu("设置为手机横屏尺寸")]
    public void SetPhoneLandscapeSize()
    {
        if (scrollView != null)
        {
            scrollView.SetContainerSize(667f, 375f);
            Debug.Log("容器尺寸已设置为手机横屏 (667x375)");
        }
    }

    /// <summary>
    /// 设置容器尺寸为平板竖屏
    /// </summary>
    [ContextMenu("设置为平板竖屏尺寸")]
    public void SetTabletPortraitSize()
    {
        if (scrollView != null)
        {
            scrollView.SetContainerSize(768f, 1024f);
            Debug.Log("容器尺寸已设置为平板竖屏 (768x1024)");
        }
    }

    /// <summary>
    /// 设置容器尺寸为平板横屏
    /// </summary>
    [ContextMenu("设置为平板横屏尺寸")]
    public void SetTabletLandscapeSize()
    {
        if (scrollView != null)
        {
            scrollView.SetContainerSize(1024f, 768f);
            Debug.Log("容器尺寸已设置为平板横屏 (1024x768)");
        }
    }

    #endregion

    #region 编辑器方法

    /// <summary>
    /// 在编辑器中重新生成测试数据
    /// </summary>
    [ContextMenu("重新生成测试数据")]
    public void RegenerateTestData()
    {
        if (Application.isPlaying)
        {
            GenerateTestData();
        }
        else
        {
            Debug.Log("重新生成测试数据功能只在运行时有效");
        }
    }

    #endregion
}


